# Generated by Django 3.1.6 on 2021-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
